MainProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('job_application_tracker.urls'), name="jobs")
]

job_application_tracker/urls.py
from django.urls import path
from .views import *

app_name = "jobs"

urlpatterns = [
    path("", ApplicataionCreateAndListView.as_view(), name="list"),
    path("application/<int:pk>", ApplicationDetailView.as_view(), name="application"),
    path("application/<int:pk>/edit/", ApplicationUpdateView.as_view(), name="update"),
    path(
        "application/<int:pk>/delete/", ApplicationDeleteView.as_view(), name="delete"
    ),
]

job_application_tracker/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class JobApplication(models.Model):
    class Meta:
        db_table = "JobApplication"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    job_description = models.TextField(blank=True)
    expected_salary = models.IntegerField()
    created_at = models.DateTimeField()

    def __str__(self):
        return self.company_name

    def get_absolute_url(self):
        return reverse("jobs:application", kwargs={"pk": self.id})

journal/models.py
from django.db import models

# Create your models here.

job_application_tracker/forms.py
from django import forms
from .models import JobApplication


class JobApplicationForm(forms.ModelForm):
    class Meta:
        model = JobApplication
        fields = ["company_name", "job_title", "job_description", "expected_salary"]

job_application_tracker/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import DetailView
from .models import JobApplication
from .forms import JobApplicationForm


class ApplicataionCreateAndListView(View):
    model = JobApplication
    template_name = "jobs_application_tracker/applications_list.html"
    fields = ["company_name", "job_title", "job_description", "expected_salary"]
    created_at = timezone.now()

    def get(self, request):
        context = {
            "object_list": self.model.objects.filter(user=self.request.user).all()
        }
        return render(request, self.template_name, context=context)

    def post(self, request):
        form = JobApplicationForm(request.POST)
        if form.is_valid():
            form.instance.created_at = timezone.now()
            form.instance.user = self.request.user
            form.save()
        return redirect("jobs:list")


class ApplicationDetailView(DetailView):
    model = JobApplication
    template_name = "jobs_application_tracker/application_detail.html"


class ApplicationUpdateView(UpdateView):
    model = JobApplication
    template_name = "jobs_application_tracker/application_edit.html"
    fields = ["company_name", "job_title", "job_description", "expected_salary"]


class ApplicationDeleteView(DeleteView):
    model = JobApplication
    success_url = reverse_lazy("jobs:list")

journal/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href='{% static "css/main.css" %}' />
  </head>
  <body>
    <div class="container py-3">
      <header>
        <div class="container">
          <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
              <li class="nav-item">
                <a href="" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="{%url 'jobs:list'%}" class="nav-link"
                  >Job Applications</a
                >
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">Journals</a>
              </li>
            </ul>
          </header>
        </div>
      </header>
      <main>{% block content %} {% endblock content %}</main>
      <footer class="pt-4 my-md-5 py-md-5 boarder-top">
        <div class="row justify-content-center align-items-center g-2">
          <div class="col-12 col-md boarder-top"><h5>Me application</h5></div>
          <div class="col-12 col-md boarder-top">
            <h5>Social Media</h5>
            <ul class="list-unstyled">
              <li class="mb-1">Instagram</li>
              <li class="mb-1">Facebook</li>
              <li class="mb-1">Twitter</li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

templates/jobs_application_tracker/application_detail.html
{%extends 'base.html'%} {%block title%}Selected Application{% endblock title%}
{% block content %}
<div>
  <img src="" class="mb-5" id="company_logo" height="300px" width="300px" />
</div>
<div
  class="card-body bg-white"
  style="color: black; border-radius: 1em; padding: 2em"
>
  <h5 class="card-title">{{ object.company_name }}</h5>
  <h6 class="card-subtitle mb-2 text-muted">{{ object.job_title }}</h6>
  <p class="card-text">{{ object.job_description }}</p>
  <h6 href="#" class="card-link">{{ object.expected_salary }}JD</h6>
  <p class="card-text" style="color:#909090">{{object.created_at}}</p>
</div>
<div>
  <span>
  <a name="" id="" class="btn btn-primary my-2 mx-2" href="{% url 'jobs:update' object.pk %}" role="button">Edit</a>
</span>
<span>
<form method="POST" action='{% url "jobs:delete" object.pk %}' style="display: inline-block;">
  {% csrf_token %}<input type="submit" value="delete" class = "btn btn-danger">
</form>
</span>

</div>
<script>
  var name = "{{object.company_name}}";
  console.log(name);
  $.ajax({
    method: "GET",
    url: "https://api.api-ninjas.com/v1/logo?name=" + name,
    headers: { "X-Api-Key": "BOvL9U0oMMJj4Nc8ppBu6A==lgfyv5PqNLUpTsv0" },
    contentType: "application/json",
    success: function (result) {
      console.log(result);
      $("#company_logo").attr("src", result[0]["image"]);
    },
    error: function ajaxError(jqXHR) {
      console.error("Error: ", jqXHR.responseText);
    },
  });
</script>
{% endblock content %}

templates/jobs_application_tracker/application_edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class = "btn btn-primary" type="submit" value="Save">
</form>
{% endblock content %}

templates/jobs_application_tracker/applications_list.html
{% extends 'base.html' %} {% block title %} Job Applictaions {% endblock title%}
{% block content %} {% for object in object_list %}
<a href='{% url "jobs:application" object.pk %}'>
  <div class="card my-5">
    <div class="card-body">
      <h5 class="card-title">{{ object.company_name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ object.job_title }}</h6>
      <p class="card-text">{{ object.job_description }}</p>
      <h6 href="#" class="card-link">{{ object.expected_salary }}JD</h6>
      <p class="card-text" style="color:#909090">{{object.created_at}}</p>
    </div>
  </div>
</a>
{% endfor %} 
<hr class="my-4">

<form method="post">
  {% csrf_token %}
  <div class="row g-3">
    <div class="col-sm-6">
      <label class="form-label">Company name</label>
      <input type="text" class="form-control" name="company_name" required="">
    </div>
    <div class="col-sm-6">
      <label class="form-label">Job Title</label>
      <input type="text" class="form-control" placeholder="" name="job_title" required="">
    </div>
    <div class="col-12">
      <div class="form-group">
        <label>Job Description</label>
        <textarea class="form-control" name="job_description" rows="3"></textarea>
      </div>
    </div>
    <div class="col-12">
      <label  class="form-label">Expected Salary <span class="" style="color:#808080">(Optional)</span></label>
      <input type="number" class="form-control" name="expected_salary">
    </div>
    <div class="col-6">
      <input type="submit" class="form-control" value= "Save"/>
    </div>
    
  </div>
</form>


{%endblock content %}